Optimize recent query by using aggregation
sparcs-kaist/new-ara-api pull request #199
Opened 2021-05-12 16:56 UTC by jungnoh

Recent view에서 최근 조회 일시를 가져오기 위해 서브쿼리를 사용하고 있었는데, 대신 aggregation을 사용합니다.

Django ORM으로는 temp table에 join하는 것이 어려워 raw query를 써서 아래와 같은 복잡한 점이 몇가지 생깁니다:
- `filter_queryset`에서 쿼리셋을 만들지 않고 action 함수에서 직접 만듭니다.
- 날쿼리는 paginator에서 처리할 수가 없어서 paginator를 따로 가져오고, 날쿼리에서 나온 데이터를 꽃아주는 방식으로 pagination을 구현했습니다.

Explain plan상으로는 확실히 빨라지는데요 (total cost 22.61 → 5.88), 아무래도 날쿼리로 인한 코드 퀄리티 저하가 좀 있는 것 같아 고민이 됩니다. 또 제 로컬에 있는 recent 테이블이 그렇게 크지 않아서 실제 성능 향상이 어느정도인지도 가늠하기 힘들고요. 프로덕션 디비를 가져와서 로드 테스팅을 해봐도 좋을 것 같습니다.

2021-05-13 07:23 UTC, victory-jooyon commented
주말에 확인해볼게요!

2021-05-17 12:22 UTC, iv-y reviewed
master가 아니라 develop에서 브랜칭해야 하지 않을까요? 그 외에 저는 LGTM입니다

2021-05-17 14:24 UTC, jungnoh commented
@iv-y 으악 뉴아라에 PR 오랜만에 남겨서..ㅎㅎ 수정하겠습니다

2021-05-18 06:03 UTC, victory-jooyon commented
내일 석가탄신일엔 꼭 확인할게요 ㅠ

2021-05-28 18:02 UTC, victory-jooyon commented
user 79706 기준 (prod db 테스팅)
`api/articles/recent` : 5.57s -> 923.77ms

2021-05-28 18:23 UTC, victory-jooyon requested changes
/recents 자체와는 관련이 없긴한데 지금 이쪽도 지금 매우 느립니다.
https://github.com/sparcs-kaist/new-ara-api/blob/develop/apps/core/serializers/article.py#L239-L290
같은 방법으로 해결할 수 있다면, 이쪽도 한번 봐주시면 좋을 것 같습니다.

prod db의 user 79706 기준 테스팅
`api/articles/235069/?from_view=recent` : 15.26s

2021-05-28 18:23 UTC, victory-jooyon commented on apps/core/views/viewsets/article.py
> +            .prefetch_related('created_by', 'created_by__profile')
prefetch_related를 select_related로 수정가능하다면 수정하는 쪽이 좋을 것 같습니다. (쿼리 2번 -> 1번으로 줄어듬)

2021-05-28 18:27 UTC, victory-jooyon requested changes

2021-05-28 18:27 UTC, victory-jooyon commented on apps/core/views/viewsets/article.py
> +            .prefetch_related('created_by', 'created_by__profile')
'parent_topic', 'parent_board' 는 함께 안가져와도되나요?

2021-05-28 18:28 UTC, victory-jooyon commented on apps/core/views/viewsets/article.py
> +            .prefetch_related('created_by', 'created_by__profile')
'parent_topic', 'parent_board' 는 함께 안가져와도되나요?

2021-05-28 22:29 UTC, jungnoh commented on apps/core/views/viewsets/article.py
> +            .prefetch_related('created_by', 'created_by__profile')
- `select_related`는 조인이라서 지금같은 raw query에는 사용할 수 없는 것으로 알고 있습니다 ㅠ
- 추가하였습니다.

2021-05-28 22:33 UTC, jungnoh commented
`get_side_articles_of_recent_article`는 전에 건드리다 말았었는데, 마무리해서 올려보도록 하겠습니다.

2021-05-30 13:56 UTC, victory-jooyon commented
더 자세히 확인결과, 변경 전후 read status 결과물이 다른 것 같습니다. 원인 파악해볼게요.

2021-05-30 14:46 UTC, victory-jooyon commented
최근본글 목록에서 글 하나 클릭해서 들어갔을때 앞뒤로 뜨는 side articles도 목록에서랑 달라요 ㅠ

2021-05-30 15:36 UTC, victory-jooyon requested changes
from_view=recent 에 대한 테스트 코드 추가해서 디버깅하면 좋을 것 같습니다.

2021-06-19 08:14 UTC, jungnoh commented
`ArticleReadLog`이 현재 사용자로 필터링되지 않아 read_status이 제대로 계산되지 않는 문제가 있었습니다.
빠져있던 Prefetch를 추가해서 해결하였습니다.
슬랙에서 이야기했던대로 read_status 정상 작동이 확인되면 recent 부분만 cherrypick해서 머지한 후, 다음 브랜치에서 테스트 추가 및 SideArticle 이슈를 해결하려 합니다.

2021-06-20 05:35 UTC, victory-jooyon commented
read status 에서 순서 안맞던 오류는 잘 해결된 것 같습니다.

![스크린샷 2021-06-20 13 44 33](https://user-images.githubusercontent.com/33751269/122662534-f6720f80-d193-11eb-9828-c434f46b4d36.png)
위 스크린린샷에서 볼 수 있듯이 화면 왼쪽에서 보이는 최근 본글이 더이상 다섯개만 보이지 않고 훨씬 더 많이 보입니다.
LIMIT 이 잘 안 먹히는것 같은데요, 이부분 제가 고쳐둘게요. 수고하셨습니다!

2021-06-20 05:47 UTC, victory-jooyon commented on apps/core/views/viewsets/article.py
>              ) recents ON recents.article_id = `core_article`.id''') \
paginator.page_size 는 settings의 default page_size를 가져오기 때문에 수정했습니다.

2021-06-20 05:49 UTC, victory-jooyon approved these changes
제가 마지막 수정자이므로 approve 합니다. @jungnoh 님 수정사항 확인해보신 후 말씀하신대로 cherry-pick 하셔서 따로 브랜치 만들어서 PR로 바로 merge해주세요.

2021-06-20 06:16 UTC, merged