Add restore, delete feature on admin page for comment,article
sparcs-kaist/new-ara-api pull request #201
Opened 2021-06-03 08:34 UTC by xhaktm3

#200 에 자세한 설명을 적었습니다.
우선 feature/issue-190/auto_delete_over-reported가 아직 머지되지않아 이쪽으로 pr을 올립니다.
리뷰 부탁드립니다.

2021-06-07 14:08 UTC, victory-jooyon requested changes
파이썬에서 함수명은 대문자로 시작하지 않습니다. PEP8 을 지켜주세요: [참고](https://www.python.org/dev/peps/pep-0008/), [헷갈리는부분요약](https://www.notion.so/sparcs/PEP8-3581b89bfdc340188f41d3cb912053cd)

2021-06-07 14:11 UTC, victory-jooyon requested changes

2021-06-07 14:11 UTC, victory-jooyon commented on apps/core/admin.py
> +        self.message_user(request, "%s 성공적으로 삭제되었습니다." % message_bit)
함수와 함수사이는 엔터로 띄워주시고, 함수명은 대문자로 시작하지 않습니다. 예를 들어 Restore_Article은 restore_article이 되어야합니다. 함수명은 snakecase를 따릅니다. 클래스명은 camelcase를 따르구요.

2021-06-07 14:16 UTC, victory-jooyon requested changes

2021-06-07 14:16 UTC, victory-jooyon commented on apps/core/admin.py
pythonic하지 않은 format string 입니다.
`"%s 성공적으로 복구되었습니다." % message_bit` 대신
`f'{message_bit} 성공적으로 복구되었습니다'` 로 해주세요. 이런 방법을 [f-string](https://docs.python.org/ko/3/tutorial/inputoutput.html) 이라고 합니다.

그리고 뉴아라는 기본적으로 string을 표현할때 single quote를 사용하고 있습니다.

2021-06-09 07:48 UTC, xhaktm3 commented on apps/core/admin.py
수정했습니다!

2021-06-09 07:48 UTC, xhaktm3 commented on apps/core/admin.py
> +        self.message_user(request, "%s 성공적으로 삭제되었습니다." % message_bit)
수정했습니다.

2021-06-09 07:49 UTC, xhaktm3 commented
> 파이썬에서 함수명은 대문자로 시작하지 않습니다. PEP8 을 지켜주세요: [참고](https://www.python.org/dev/peps/pep-0008/), [헷갈리는부분요약](https://www.notion.so/sparcs/PEP8-3581b89bfdc340188f41d3cb912053cd)

올려주신 PEP8에관한 자료들 꼼꼼히 읽어보았습니다. 다음부터는 PEP8을 지켜 코딩하도록 하겠습니다. 잘 배우고있습니다. 감사합니다 주연님!

2021-06-19 08:20 UTC, cjeon commented on apps/core/admin.py
> +            e.save()
django 는 잘 모르는데요, 이러면 혹시 n번 save가 호출되나요? 만약 그렇다면 하나의 transaction으로 처리하면 좋을 것 같습니다. (이미 그렇게 처리되고 있으면 무시해주세요!) L179 도 동일합니다.

2021-06-19 08:20 UTC, cjeon commented on apps/core/admin.py
> +        self.message_user(request, f'{message_bit}성공적으로 삭제되었습니다.')
minor 한데요, 이렇게 string concatenation을 하면 띄어쓰기 없이 `1개의 게시물이성공적으로 삭제되었습니다.` ← 이렇게 나오는 것 아닌가요? L185도 동일한 질문입니다.

2021-06-19 08:24 UTC, jungnoh commented on apps/core/admin.py
> +            e.save()
```py
queryset.filter(deleted_at=timezone.datetime.min.replace(tzinfo=timezone.utc)).update(deleted_at=timezone.now())
```
로 수정하면 UPDATE 쿼리 하나만 날아갑니다!

2021-06-28 13:29 UTC, xhaktm3 commented on apps/core/admin.py
> +        self.message_user(request, f'{message_bit}성공적으로 삭제되었습니다.')
지적 감사합니다! 수정했습니다 :)

2021-06-29 04:56 UTC, xhaktm3 commented on apps/core/admin.py
> +            e.save()
@jungnoh 

save()와 다르게 update() 메소드는 post_save signal을 보내지 못합니다. 따라서 models > signals > on_delete_cascade.py 에서 deleted_at 변화에 대한 삭제처리를 진행하지못해요. 그래서 일일히 save()를 썼었는데, cjeon님 말씀대로 transaction처리가 필요해보입니다. @transaction atomic을 걸어 해결하면 될까요?

2021-06-29 05:36 UTC, jungnoh commented on apps/core/admin.py
> +            e.save()
ㅇㅇ 트랜잭션 써도 됩니다

2021-07-02 06:19 UTC, victory-jooyon commented on apps/core/admin.py
> +            e.save()
이 함수 만드신 목적이 몇개 삭제 되었는지 메시지를 받고 싶어서인가요? 단순히 게시글 삭제시 댓글도 삭제하고 싶었던 거면, 원래도 admin페이지에서 게시물 삭제 눌러도 알아서 deleted_at 채워지면서, 게시물 조회기록이나 댓글 같이 삭제되어서요. (단, 대댓글은 삭제 안됨)

2021-07-02 06:25 UTC, victory-jooyon commented on apps/core/admin.py
> +            e.save()
issue에서 목적 확인했고, 굳이 이부분 수정하지 않아도 댓글도 함께 삭제됩니다. https://github.com/sparcs-kaist/new-ara-api/issues/200#issuecomment-872750439 에서 확인하실 수 있습니다.

2021-07-02 06:27 UTC, victory-jooyon commented on apps/core/admin.py
> +            e.save()
어느 상황에서 테스트를 해보면서 댓글 삭제가 안된다고 확인을 하신건지 궁금합니다.

2021-07-05 14:39 UTC, xhaktm3 commented on apps/core/admin.py
> +            e.save()
헉 주연님 죄송합니다. 제가 코드를 리뷰하면서 
https://docs.djangoproject.com/en/3.2/ref/contrib/admin/actions/ 의 노란박스안에 delete action에 관한 항목을 읽고, 코드에model.delete()를 오버라이드한 부분을 찾지못해 그렇게 생각했었습니다.

2021-07-05 16:26 UTC, jungnoh commented on apps/core/admin.py
> +            e.save()
요거 resolve 된걸까요??

2021-07-05 16:47 UTC, jungnoh requested changes
전부 자잘한 수정사항들이네요. 수고하셨어요~!

2021-07-05 16:47 UTC, jungnoh commented on apps/core/admin.py
클래스와 클래스 사이에는 빈칸이 2개입니다. (PEP8 규칙)
아무래도 pre-commit hook 설치가 되어 있지 않으신것 같은데,
```bash
poetry install
pre-commit install
```
한번 실행해 주세요. 이제 커밋하실 때 자동으로 이런 문제들은 수정될거에요

2021-07-05 16:47 UTC, jungnoh commented on apps/core/admin.py
> +    title = _('Hidden Article')
i18n 텍스트도 같이 넣어주세요. 이렇게 떠요
![스크린샷 2021-07-06 오전 1 36 27](https://user-images.githubusercontent.com/11422210/124500360-9669a300-ddfa-11eb-9d09-36e0f4e92a33.png)

2021-07-05 16:47 UTC, jungnoh commented on apps/core/admin.py
> +        self.message_user(request, f'{message_bit} 성공적으로 복구되었습니다.')
진짜 사소한거긴 한데..
```py
self.message_user(request, f'{rows_updated}개의 댓글(들)이 성공적으로 복구되었습니다.')
```
이렇게 하는 편이 더 간결할 것 같아요. 제 취향이니 편하신 대로 하시면 됩니다.

2021-07-05 16:47 UTC, jungnoh commented on apps/core/admin.py
> +            ('1', _('숨김 처리된 글')),
`1`처럼 의미 없는 값보다는 `hidden` 처럼 의미 있는 값이 더 좋습니다.

2021-07-06 01:39 UTC, victory-jooyon commented on apps/core/admin.py
> +            e.save()
@xhaktm3 네네 restore 관련 기능만 남기도 delete 관련해서 작업하신부분은 다시 삭제하면 될 것 같습니다!

2021-07-12 03:08 UTC, xhaktm3 commented on apps/core/admin.py
감사합니다!

2021-07-12 03:10 UTC, xhaktm3 commented on apps/core/admin.py
> +        self.message_user(request, f'{message_bit} 성공적으로 복구되었습니다.')
알겠습니다. 이쪽이 간결한 것 같네요.

2021-07-12 03:10 UTC, xhaktm3 commented on apps/core/admin.py
> +            ('1', _('숨김 처리된 글')),
수정했습니다

2021-07-12 03:30 UTC, xhaktm3 commented on apps/core/admin.py
> +    title = _('Hidden Article')
기능 추가했습니다.

2021-07-12 09:47 UTC, victory-jooyon approved these changes
- django 3.2 부터 제공되는 [@admin.action](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/actions/#the-action-decorator) 을 사용하기 위하여 django를 3.1 에서 3.2 로 update 했습니다.
@jessyoon14 @jungnoh @xhaktm3 이 PR이 merge되면 다들 poetry update 를 다시 해주시면 좋을 것 같아요.

- article을 번역할때, '문서'와 '게시물'이 혼용되고 있어 모두 '게시물'로 통일했습니다.

2021-07-12 11:42 UTC, merged