Feature/issue 196/anonymous json response
sparcs-kaist/new-ara-api pull request #203
Opened 2021-06-28 13:54 UTC by jessyoon14

API response 익명화 로직입니다.

익명 article의 get request가 들어오면, 글쓴이를 식별 가능한 정보(user id, 닉네임등)를 빼고, 닉네임 "익명"과  랜덤한 프로필 이미지를 넣어서 보냅니다.

익명 comment의 get request가 들어오면, 마찬가지로 글쓴이 식별 가능한 정보 (user id, 닉네임 등)을 빼고, `user id + article id + secret key`를 해싱한 값을 사용하여 '익명의 개구리 1ab'와 같은 닉네임 + 랜덤 프로필 이미지로 리턴합니다. 
물론, 같은 사용자가 한 게시글 내에 여러 개의 댓글을 달 경우 닉네임과 프로필 이미지는 다 같습니다. 
또한, 게시글의 글쓴이가 본인의 글에 단 댓글은 '글쓴이'로 표시됩니다.

2021-06-28 14:06 UTC, jungnoh commented
제가 지금 한것처럼 base를 바꾸거나, 4개 커밋만 develop에서 딴 새로운 브랜치로 cherry-pick 하면 좋을것 같아요

2021-06-28 14:31 UTC, jungnoh requested changes
수고하셨습니다!
그런데 테스트가 아예 없네요..ㅜㅜ 테스트 추가는 이번 PR에서 해주셨으면 좋겠습니다.

2021-06-28 14:31 UTC, jungnoh commented on apps/core/serializers/comment.py
> +            errors.append(exceptions.ValidationError(gettext('This article is written by a시 user you blocked.')))
typo

2021-06-28 14:31 UTC, jungnoh commented on apps/core/serializers/comment.py
> +             '오리너구리', '보노보노', '개미핥기', '치타', '사자', '구렁이', '도마뱀', '개구리', '올빼미', '부엉이']
상수는 함수 바깥으로 빼주세요 (+`NOUNS`로 이름 변경)
그리고 로그인에서 닉네임 만드는 코드에 동물 이름 배열이 있는데 (`apps/user/views/viewsets/user.py:L26`), 이걸 재사용 하는 건 어떨까요?

2021-06-28 14:31 UTC, jungnoh commented on apps/core/serializers/comment.py
> +    return default_picture
중복되는 procedure이니 따로 함수로 빼서 article 쪽과 재사용 가능하게 해주세요.

2021-06-28 14:31 UTC, jungnoh commented on apps/core/serializers/article.py
> +    temp_num = numbers[hash_val % len(numbers)]
이렇게 하면 색깔이랑 번호가 항상 같지 않을까요? (둘다 mod 3)

2021-06-28 14:31 UTC, jungnoh commented on apps/core/serializers/comment.py
> +    user_profile_picture = make_random_profile_picture(hash(user_unique_encoding))
해싱을 한번 했기 때문에 또 hash를 사용하는것은 불필요합니다. 대신 `user_hash`에서 하위 비트 몇개만 가지고 와서 넣어주는것이 더 좋을 것 같습니다.

2021-06-28 14:31 UTC, jungnoh commented on apps/core/serializers/article.py
> +    user_profile_picture = make_random_profile_picture(hash(user_unique_encoding))
`hash` builtin 만 사용하는 것은 보안상 문제가 있습니다 (cryptographic hash function이 아님; https://stackoverflow.com/questions/7646520/is-this-an-appropriate-use-of-pythons-built-in-hash-function )
아래처럼 sha-2를 쓰는 구현이 더 좋을 것 같습니다.

2021-06-28 14:31 UTC, jungnoh commented on ara/settings/env.py
> +    HASH_SECRET_VALUE=(int, os_environ.get('HASH_SECRET_VALUE', 1234)),
실수하면 secret으로 1234 들어가니까 default 없는 편이 더 좋을 것 같습니다.

2021-07-01 16:08 UTC, jessyoon14 commented on apps/core/serializers/comment.py
> +    return default_picture
함수로 빼서 serializers/article.py에 만들어 놓고 comment.py에서 article을 import하게 하면 좋을까요? 혹시 다른 곳에 있는게 더 자연스러울까요?

2021-07-01 16:14 UTC, jessyoon14 commented on apps/core/serializers/comment.py
> +             '오리너구리', '보노보노', '개미핥기', '치타', '사자', '구렁이', '도마뱀', '개구리', '올빼미', '부엉이']
`apps/user/views/viewsets/user.py:L26`의 NOUNS, ADJECTIVES를 원래 속해있던 함수(_make_random_name()) 밖으로 빼고,
`serializers/comment.py`에서 import해서 사용할게요 :)

2021-07-01 16:18 UTC, jessyoon14 commented on apps/core/serializers/article.py
> +    temp_num = numbers[hash_val % len(numbers)]
헛 그러네요..! 그러면 `temp_num = numbers[(hash_val/3) % len(numbers)]`로 수정해볼게요

2021-07-01 16:44 UTC, jessyoon14 commented on apps/core/serializers/article.py
> +    user_profile_picture = make_random_profile_picture(hash(user_unique_encoding))
comment의 경우, 한 게시글 내에서 댓글의 작성자들을 구분해야 하니 user id를 sha-224로 해싱하여 프론트에 넘겨주었습니다.
article의 경우, 게시글 작성자를 구분할 필요가 없으니 sha를 사용하지 않고, 간단하게 user id: 0으로 넘겨주었습니다. (프론트에 보내주는 작성자 관련 정보가 profile picture 밖에 없어, encryption이 필요 없다고 생각하였습니다.) 
profile picture를 랜덤하게 만드는 것은 단순한 작업이라서 단순 hash를 사용했는데, 그래도 sha를 쓰는 것이 좋을까요? 

그리고 hash에 대한 설명 감사합니다! 잘 모르고 사용했었는데 보내주신 링크 읽어보니 앞으로 올바르게 사용할 수 있을것 같아요 :)

2021-07-01 17:13 UTC, jessyoon14 commented
말씀해주신대로 develop에서 브랜치 새로 파서 cherry-picking 했습니다. 위에 남겨주신 코멘트에 제가 질문드린 부분 확인해주시면 이 PR은 닫을게요

2021-07-05 16:17 UTC, jungnoh commented on apps/core/serializers/article.py
> +    user_profile_picture = make_random_profile_picture(hash(user_unique_encoding))
우선 용어 한가지만 정리드리자면, 해쉬 함수를 사용하는 목적은 encryption이 아닙니다. 비밀 정보(key)를 가지고 있는 사람이 암호문을 평문으로 해독할 수 있는 기능을 원할 때 암호화를 사용하는 것인데, 우리가 필요한 기능은 그게 아니고 해쉬 함수의 역할도 그게 아닙니다.

이 경우에서 해쉬함수를 사용하는 것은 `user_unique_num` -> `user_profile_picture` 로 일관된 mapping을 원하기 때문입니다. 또 익명 기능을 구현하려 하는 것이기 때문에, 역방향 (`user_profile_picture` -> `user_unique_num`)을 알 수 없어야 합니다. 그렇기 때문에 비밀 키를 섞은 상태에서 sha-2 와 같은 cryptographic hash function을 사용하는 것입니다.

물론 최종 결과의 경우의 수가 9가지에 불과하고, 이걸 역추적 하는 것이 현실적으로 있을 만한 공격인지를 생각해 보면.. 이렇게 보안성을 고려하지 않아도 될 수도 있습니다. 그러나 제 생각에는 이 상황에서 builtin `hash` 대비 sha-2가 가지는 단점이 없어서 (하드웨어 가속이 되니까 성능 하락이 무시할 만한 정도라고 생각되기 때문에), 굳이 안전성이 떨어지는 방법을 택할 필요는 없다고 생각합니다.

그런데 말씀해 주신 것처럼 `obj.created_by.id==0` 이라면 위의 논의가 전혀 필요 없어지게 됩니다. `user_unique_num`에 숨겨야 할 값 자체가 없으니, 해쉬를 하는 것도, secret 섞는 것도 무의미합니다. 일관되고 적당한 psuedo-random 값을 줄 수 있는 방법으로 대체하면 되겠죠. 예를 들어서 `obj.id + obj.created_at.second` 같은 값을 `user_unique_num`으로 두고, `user_profile_picture = make_random_profile_picture(user_unique_encoding % 9)`로 하면 충분히 랜덤'처럼' 보일 것입니다.

한줄 요약을 드리자면... 사용자 pk가 0이면 해쉬 자체를 안해도 된다고 생각합니다.

2021-07-05 16:19 UTC, jungnoh commented
확인드렸으니 이 PR은 닫도록 하겠습니다. 코멘트 드린 부분 반영 필요하다고 생각 되시면 #206 에 반영 부탁드리겠습니다.

2021-07-05 16:19 UTC, closed without merging