NEW: Add anonymized user profile for anonymous posts
sparcs-kaist/new-ara-api pull request #204
Opened 2021-07-01 17:15 UTC by jessyoon14

이전 PR [#203 ]의 브랜치에서 cherry-picking한 브랜치의 PR입니다.

2021-07-01 17:42 UTC, jungnoh approved these changes
LGTM!

2021-07-01 17:44 UTC, jungnoh requested changes
코드상에 문제는 없는데 테스트 통과를 못하네요. 테스트 통과하도록 수정만 되면 문제 없을 듯 합니다.

2021-07-01 17:46 UTC, jessyoon14 commented
감사합니다!
지금 테스트 통과 못하는게, migration할 때 articles의 hidden_at에 default를 안주어서입니다. 모든 article이 hidden_at column 값이 없다고 db에 못들어가고 있네여..
이거 지금 해결이 안되서, 좀 더 시간이 걸릴 것 같습니다. 이 부분만 디버깅하면 테스트 코드는 간단해서, 주말까지 완료할게요.

2021-07-02 01:19 UTC, victory-jooyon commented
@jungnoh @jessyoon14 이런 익명처리를 serializer에서 하면, 해당 article이 click될때마다 이 연산이 계속 일어나게 되는데, (나중에는 댓글에서까지 이 연산이 다 일어날거고요) 혹시 db상에서 article 테이블에 created_by 외에 created_by_nickname, created_by_profile 칼럼을 추가하는건 어떨까요?

익명글은 유저가 닉네임 바꾸거나, 프로필 변경 하는거랑 상관이 아예 없으니까, 그냥 처음부터
created_by_nickname 이랑 created_by_profile 을 이 PR에서 열심히 만든 함수들 돌려서 채워주고,

일반글은 db상에서는 created_by_nickname이랑 created_by_profile을 비워두고, serializer에서  created_by.nickname, created_by.profile 내용으로 해당 필드들 채워서 내려주는 형태로요.

그러면 프론트에서는 공통적으로 created_by_nickname, created_by_profile 을 받아서 화면 뿌려주면 될것 같은데.

2021-07-02 05:21 UTC, jessyoon14 commented
말씀하신대로 db에 익명글 관련 필드들을 새로 만드는 쪽이 훨씬 연산을 줄일 수 있겠네요! 그 방향으로 새로 수정해볼게요. 감사합니다~

2021-07-03 08:08 UTC, victory-jooyon commented
슬렉 메시지 옮겨옵니다. 

생각을 해봤는데요,
- 우선 created_by_nickname, created_by_profile 칼럼을 DB에 넣는건 반대합니다. 정규화가 너무 깨져버리고, 향후 유지보수가 어려워질 것 같습니다. 다른 사람이 봤을 때 nickname, profile이 created_by_id에 대해 functional dependency를 가진다고 생각하기 쉬운데, 충분히 주의를 기울이지 않으면 버그가 나기 쉬울 것 같습니다.
- 말씀하신 것처럼 Serializer에서 연산을 하면 한 object에 여러 번 연산이 일어나기 때문에 좋지 않을 것 같습니다. 또 Serializer는 주어진 객체를 응답 형태로 변환하는 mapper라고 생각하는데, 익명 처리는 일종의 비즈니스 로직이니 Serializer에 있는 것도 디자인 상으로도 좋지 못하다고 생각됩니다.
- 대신 적절한 코드의 위치는 모델일 것 같습니다. Article, Comment 모델에 익명을 고려한 작성자 정보를 가져오는 메소드를 추가하고, 거기에 이번 PR에서 만든 로직을 넣어주면 될 것 같습니다. @cached_property를 걸어주면 연산도 한번만 할테고요.
- 해싱하는 것이 DB query만큼 응답 시간에 큰 비중을 차지할지는 잘 모르겠지만, 테스트를 해봐서 실제로 비중이 크면 따로 캐싱을 해도 될 것 같습니다. 메세지가 (object id+author id)이니 이 값을 key, 해쉬를 value로 해서 Redis에 넣어주면 될것 같네요.
그래서 제 생각에 가장 나은 개선방안은 다음과 같습니다.
- API상에서 보이는 사용자(Article.get_visible_user?)를 구하는 로직을 모델로 빼고, @cached_property 적용
- 해시하는 연산 비용이 너무 큰 경우, 해싱 알고리즘을 바꾸거나 redis로 캐싱

2021-07-03 13:51 UTC, jungnoh commented
@victory-jooyon 감사합니당

2021-07-05 11:40 UTC, jessyoon14 commented
감사합니다. 위에 말씀해주신 로직대로 새 브랜치(feature/issue-196/anonymous-writers-in-model)에서 진행하고, 현 PR 닫습니다.

2021-07-05 11:40 UTC, closed without merging

2021-07-05 14:09 UTC, victory-jooyon commented
#206 PR로 대체합니다.