다른 사용자의 게시글 목록을 조회할 때, 익명 게시글 제외
sparcs-kaist/new-ara-api pull request #217
Opened 2021-07-21 14:24 UTC by jessyoon14

마이페이지에서 내가 쓴 글을 볼때, 그리고 게시글에서 작성자 이름을 클릭해서 그 작성자의 모든 글을 볼때 아래 api를 사용합니다:
api/articles/?created_by=1

다른 사용자의 글 목록을 조회할 때는 익명 게시글이 보이지 않고, 자신의 작성 글 목록에는 자신이 작성한 익명 게시글들이 보이도록 수정하였습니다.

2021-07-22 04:09 UTC, jessyoon14 commented
테스트 fail 하네요ㅠ 테스트 패스하게 수정해서 다시 push할게요

2021-07-27 13:05 UTC, jungnoh requested changes
코드의 로직을 설명하는 주석 (66, 68, 69라인)은 가급적 자제하는 것이 좋습니다.
클린코드 책에서 주석 관련 부분 한번 읽어보시면 도움이 될 것 같습니다.

2021-07-27 13:05 UTC, jungnoh commented on apps/core/views/viewsets/article.py
> +                    queryset = queryset.exclude(is_anonymous=1)
`True`를 사용해 주세요

2021-07-27 13:05 UTC, jungnoh commented on apps/core/views/viewsets/article.py
> +
불필요하게 조건이 깊어지는 것 같은데, 그냥 인라이닝 해서
`if created_by is not None and int(created_by) != self.request.user.id` 하면 한단계 덜 깊어질것 같아요

2021-07-30 13:37 UTC, jungnoh approved these changes

2021-07-30 13:37 UTC, jungnoh commented on apps/core/views/viewsets/article.py
> +            if created_by and int(created_by) != self.request.user.id:
사실 이거 잘못된 값 들어가면 `int()`에서 익셉션 떠서 500 날것 같긴 한데.. 그냥 넘어가도 될것 같네용

2021-08-02 10:37 UTC, jessyoon14 commented on apps/core/views/viewsets/article.py
> +            if created_by and int(created_by) != self.request.user.id:
@jungnoh 님 꼼꼼히 봐주셔서 감사합니다.
이 케이스를 더 잘 처리하려면 어떻게 해야될까요?
catch exception해서 그 경우... 무언가를 해야될 것 같은데, 그 무언가가 뭘까요?

2021-08-02 10:51 UTC, jungnoh commented on apps/core/views/viewsets/article.py
> +            if created_by and int(created_by) != self.request.user.id:
제생각에는 에러가 나기 전에 `self.request.query_params`를 validate 하는게 나을것 같아요.

2021-08-02 11:42 UTC, jessyoon14 commented on apps/core/views/viewsets/article.py
> +            if created_by and int(created_by) != self.request.user.id:
아아 그렇군요. 그러면 그렇게 수정할게요. 감사합니다!

2021-08-06 11:59 UTC, jessyoon14 commented on apps/core/views/viewsets/article.py
> +            if created_by and int(created_by) != self.request.user.id:
@jungnoh 

input validation을 하면서 테스트해봤는데요, created_by에 잘못된 값이 들어가면 62번째 줄에서 다음과 같은 로그가 뜨며 `if self.action == 'list'` 안으로 들어가지 못합니다.
```
Not Found: /api/user_profiles/m/
[06/Aug/2021 20:56:16] "GET /api/user_profiles/m/ HTTP/1.1" 404 23
Bad Request: /api/articles/
```

따라서 (64줄) `if self.action == 'list':` 안에서 input validation을 할 필요가 없다고 생각됩니다.
그래서 이 PR은 이대로 merge 하겠습니다..!

2021-08-06 12:00 UTC, merged