Fix search on recents and scraps
sparcs-kaist/new-ara-api pull request #218
Opened 2021-07-25 17:44 UTC by iv-y

- Fixed search on scraps
  - 새로운 filterset을 만들기보다, 어차피 scrap의 경우 이미 scrapped_by로 queryset이 filter되고 있는 만큼 거기에 같이 얹어가도록 구현했습니다. 
- Fixed search on recents
  - es에서 얻어온 id_set을 이용해 subquery 단에서부터 미리 글을 거를 수 있도록 구현했습니다. 
  - `search_restriction_sql`을 str.join 등을 이용해 직접 만들고 있는데, 이렇게 하는 것이 최선일지 의견 남겨 주시면 감사하겠습니다.

2021-07-26 12:35 UTC, jungnoh requested changes

2021-07-26 12:35 UTC, jungnoh commented on apps/core/views/viewsets/article.py
> +                search_restriction_sql = 'AND `core_articlereadlog`.`article_id` IN (' + ', '.join(map(str, id_set)) + ') '
이렇게 하면 prepared stmt가 안돼서, `AND ~~~ IN %s`로 한다음에 257라인에서 배열로 넣어주는 쪽이 나아보여요.
(제 기억상 IN 안에 list도 장고가 알아서 풀어줍니다)

2021-07-26 12:35 UTC, jungnoh commented on apps/core/views/viewsets/article.py
> +                search_restriction_sql = 'AND FALSE'
결과 어차피 없는거면 아래 쿼리 태우지 말고 빈거 리턴하는게 낫지 않을까요?

2021-07-26 12:41 UTC, jessyoon14 reviewed
위에 정훈님께서 말해주신 부분 수정해주시면 로컬에서 작동하는지 확인해볼게요

2021-07-30 13:43 UTC, iv-y commented on apps/core/views/viewsets/article.py
> +                search_restriction_sql = 'AND `core_articlereadlog`.`article_id` IN (' + ', '.join(map(str, id_set)) + ') '
반영했습니다. list도 자동으로 풀어주네요 👍

2021-07-30 13:44 UTC, iv-y commented on apps/core/views/viewsets/article.py
> +                search_restriction_sql = 'AND FALSE'
반영했습니다.

2021-07-30 13:47 UTC, jungnoh approved these changes
🥳

2021-08-02 13:26 UTC, victory-jooyon reviewed
저번에 정훈님이 recent 수정하실때도 그렇고, 이부분 조금 정교하게 짜여진 테스트코드가 있으면 좋을 것 같다는 생각이 드네요 ㅠㅠ 저번에 #199 리뷰할때도 힘들었거든요. 수고하셨고, 저도 틀린부분 없는지 테스트해보고 다시 코멘트 남기도록 할게요. 얼핏봤을때 스크랩부분은 문제 없을 것 같습니다.

2021-08-02 13:26 UTC, victory-jooyon commented on apps/core/views/viewsets/article.py
> +                WHERE (`core_articlereadlog`.`deleted_at` = '0001-01-01 00:00:00' AND `core_articlereadlog`.`read_by_id` = %s {search_restriction_sql})
제 기억에 @jungnoh 님이 전에 prepared statement에서는 %s 로 해야한다고 했던 것 같은데 이부분은 상관없나 정확히 모르겠네요. [참고](https://sparcs.slack.com/archives/CQ4QFM8HX/p1624168036001100?thread_ts=1624167934.001000&cid=CQ4QFM8HX)

2021-08-02 13:31 UTC, jungnoh commented on apps/core/views/viewsets/article.py
> +                WHERE (`core_articlereadlog`.`deleted_at` = '0001-01-01 00:00:00' AND `core_articlereadlog`.`read_by_id` = %s {search_restriction_sql})
prepared stmt 들어가기 전에 포맷 스트링을 포맷하는.. 그런거라서 이 경우에는 문제가 없습니다.
#199 에서 말씀드렸던 거는 fstring의 인수에 필드 값이 들어간거고, 이 경우에는 fstring의 인수에 쿼리의 일부가 (필드X) 들어간 상황입니다.

2021-08-02 13:33 UTC, iv-y commented on apps/core/views/viewsets/article.py
> +                WHERE (`core_articlereadlog`.`deleted_at` = '0001-01-01 00:00:00' AND `core_articlereadlog`.`read_by_id` = %s {search_restriction_sql})
앗, 저 부분의 `{search_restriction_sql}`은 유저 데이터를 처리하는 부분이 아니고, where절 조건식 자체를 바꾸어야 해서 넣었습니다! 위쪽 if를 보시면 `search_restriction_sql`이 빈 문자열 아니면 `AND ~~~ IN %s`인 두 가지 경우밖에 없어요

2021-08-02 13:53 UTC, victory-jooyon commented
최근본글에서 검색한후에 글 하나 클릭해서 들어갔을때 side_articles에서 문제가 있네요.

목록:
![image](https://user-images.githubusercontent.com/33751269/127872768-b2e6a573-0dbf-4b7f-a06b-24271ca61f80.png)
에서 가운데껄 들어가보면
![image](https://user-images.githubusercontent.com/33751269/127872818-05d43419-4f1a-4b36-ae9f-65db4dc92f55.png)

2021-08-02 13:56 UTC, victory-jooyon requested changes
recent -> 검색 -> side articles 로직 한번 확인부탁드려요.

2021-08-03 04:23 UTC, victory-jooyon commented
이거 그리고 가능하시면 recent랑 recent의 sidearticles 테스트코드도 부탁드릴게요..!

2021-08-07 12:38 UTC, victory-jooyon commented
prod db 기준으로 테스트
제 userid: 79706

1. 최근본글에서 '모니터' 검색
- 프론트 url: https://newara.sparcs.org/myinfo?board=recent&query=%EB%AA%A8%EB%8B%88%ED%84%B0
- 백엔드 api: https://newara.sparcs.org/api/articles/recent/?main_search__contains=%EB%AA%A8%EB%8B%88%ED%84%B0

2. 목록에서 결과
![image](https://user-images.githubusercontent.com/33751269/128600185-a7b82c19-7b25-4d8f-add5-31d11021b89c.png)
![image](https://user-images.githubusercontent.com/33751269/128600197-146566ed-6ca8-405f-82f5-3d05c634dedd.png)

3. 이중에서 가운데에 있는 236620 게시물을 클릭
- 프론트 url: https://newara.sparcs.org/post/236620?from_view=recent&search_query=%EB%AA%A8%EB%8B%88%ED%84%B0
- 백엔드 api: https://newara.sparcs.org/api/articles/236620/?from_view=recent&search_query=%EB%AA%A8%EB%8B%88%ED%84%B0

4. side articles 확인
![image](https://user-images.githubusercontent.com/33751269/128600328-571601e4-8084-4d4c-b432-b2df1867e7a2.png)
![image](https://user-images.githubusercontent.com/33751269/128600337-16c62180-766d-4ab9-b911-8671446da652.png)

2021-08-07 14:37 UTC, victory-jooyon commented
[슬렉에서 해주신 얘기](https://sparcs.slack.com/archives/CV6H8N4EM/p1628068641015400)에 보태보자면 내려주는 side_articles 자체가 틀린거라서 프론트에 문제가 있는건 아닌 것 같고요, 저도 로컬에 있는 몇 안되는 문서가지고 할때는 문제 없는데 prod db 가지고 할때 문제가 생기네요.
오늘은 재현까지가 최선인 것 같고, 제대로 디버깅 해보려면 저도 회사일도 있고 해서 시간이 좀 걸릴 것 같습니다.

2021-08-08 08:14 UTC, iv-y commented
흠, 검색을 안 할 때도 side_articles가 이상하게 나오는 걸 보면 뭔가 쿼리셋 만드는 부분을 다시 검토해야 할 것 같긴 하네요... 테스트를 좀 만들어두도록 하겠습니다. 

우선 이 PR은 머지하고, side_articles 관련해서 새로 브랜치를 만들어서 살펴보는 게 어떨까 싶어요.

2021-08-08 10:16 UTC, victory-jooyon approved these changes
말씀하신대로 이 PR 멘션해서 side articles 관련 수정 PR 새로 열어주세요.
테스트도 그땐 꼭 추가..

2021-08-09 00:04 UTC, jungnoh commented
(이 PR과 관계없이) 전반적으로 리스트 가져오는 부분 리팩토링이 필요할것 같네요.. 한 메소드에 책임이 너무 많아요

2021-08-09 11:50 UTC, merged