Bugfix/issue 222/fix broken profile image link
sparcs-kaist/new-ara-api pull request #226
Opened 2021-08-07 02:06 UTC by jessyoon14

익명 글/댓글에 대한 프로필 사진의 경우, PublicUserProfileSerializer를 거치지 않아 프로필 사진 링크가 미완성이었습니다.
따라서 익명 글/댓글의 프로필 사진 링크를 완성하였습니다.

<img width="338" alt="Screen Shot 2021-08-07 at 11 06 38 AM" src="https://user-images.githubusercontent.com/48045424/128584610-dabae907-746f-41b0-9fdb-a70fb2c42b22.png">

2021-08-07 02:33 UTC, iv-y requested changes
import만 조금 고쳐주세요! 수고하셨습니다 :)

2021-08-07 02:33 UTC, iv-y commented on apps/core/models/article.py
> +from ara.settings import HASH_SECRET_VALUE, AWS_S3_BUCKET_NAME
이 부분에 불필요한 import만 지워주시면 될 것 같아요!

2021-08-07 02:43 UTC, jungnoh commented
테스트도 짜주세요

2021-08-07 04:47 UTC, jessyoon14 commented
@jungnoh 감사합니다. 테스트 추가했습니다~

2021-08-07 09:16 UTC, jungnoh commented
테스트 통과되면 approve할게요

2021-08-08 14:44 UTC, jessyoon14 commented
@jungnoh 테스트 케이스 수정하였습니다.

2021-08-09 00:01 UTC, jungnoh requested changes

2021-08-09 00:01 UTC, jungnoh commented on tests/test_user.py
> +            assert False, 'Bad URL for anonymous article profile picture'
[URLValidator 소스](https://github.com/django/django/blob/ee46722cb9c860abec4d370adff052d0c1622d34/django/core/validators.py)를 보니 그냥 `URLValidator(profile_picture_url)` 해도 될것 같아요

2021-08-09 13:17 UTC, jungnoh approved these changes

2021-08-09 13:19 UTC, iv-y approved these changes
LGTM!

2021-08-16 10:32 UTC, merged