Crawler overlap delete
sparcs-kaist/new-ara-api pull request #227
Opened 2021-08-07 03:56 UTC by xhaktm3

issue #225 

포탈 크롤링 시 중복되는 내용, 제목의 게시글들이 여러번 크롤링 되지않도록 수정했습니다.
apps>core>scripts>crawl_hour() 함수에 db에 저장된 게시글들에 추가할 게시글의 내용,제목을 가진 게시글이 있는지 exist에 전달합니다.

모든 중복 게시글을 제거하는 것은 아니며, 내용은 같지만 미세한 차이가 존재할 경우 (문장사이의 공백공간이 다르는 등) 게시물은 중복이라 판단되지 못합니다.

2021-08-07 06:52 UTC, jessyoon14 approved these changes
로컬에서 잘 돌아가는 것 확인했습니다. 아래 마이너한것만 수정 고려해주시면 감사하겠습니다 :)

2021-08-07 06:52 UTC, jessyoon14 commented on apps/core/management/scripts/portal_crawler.py
> +        else:
if-else 대신 if not exist로 합치는게 깔끔할 것 같습니다.

2021-08-07 06:52 UTC, jessyoon14 commented on apps/core/management/scripts/portal_crawler.py
> +        exist = Article.objects.filter(title=info['title'],content_text=info['content_text'])
가독성을 위해 article_exist로 하면 좋을것 같아요

2021-08-07 07:14 UTC, xhaktm3 commented on apps/core/management/scripts/portal_crawler.py
> +        else:
수정했습니다1

2021-08-07 07:15 UTC, xhaktm3 commented on apps/core/management/scripts/portal_crawler.py
> +        exist = Article.objects.filter(title=info['title'],content_text=info['content_text'])
수정했습니다

2021-08-07 09:15 UTC, jungnoh commented on apps/core/management/scripts/portal_crawler.py
> +                print(f'crawled id: {a.id} - {a.title}')
이부분이 `if not article_exist:` 밑으로 들어가는게 맞나요? (잘 몰라서요)

2021-08-07 10:33 UTC, victory-jooyon requested changes
1. 현재는 link를 기준으로 이미 크롤링 했던건지/안했던 건지를 판단합니다. 이제는 이미 크롤링 했었는지 안했었는지 외에도 이미 크롤링을 했던 내용인지에 대한 판단이 함께 들어가게 되는데요,
현재 윤수님은 내용중복 판단을 우선하고, 그 다음에 크롤링했었는지/안했었는지를 판단하는 순서로 가게 되는데 (article_exist 연산 후 created 판단), 이부분 가장 효율적일 수 있도록 한번 고민해보셨으면 좋겠습니다.

제 생각에는,
- 포탈 공지글들을 살펴보시면 같은 제목/내용의 글들은 같은 시간으로 올라오게 됩니다.
- 따라서, 어차피 동시에 크롤러에 들어오게 되는데요,
- 크롤러가 같은 내용의 공지글을 여러개 긁게 되면 생성되는 하나의 article에 url 필드에 그중 가장 최신 공지글의 링크를 넣고, 그러면 링크를 활용해서 다음크롤러가 어디서부터 긁으면 되는지 판단할때 지금과 차이가 없게 될 것 같습니다.
- 그렇게 크롤러가 시작지점을 판단하게 되면, 지금처럼 get_or_create 하기보다는 한번에 Article object 들 만들어두고 bulk_create 하면 좋지 않을까 싶네요!

제가 깊이 생각하지 못한 지점도 분명 있을 것 같은데, 윤수님 고민해보시고 이해 안되는 부분들 말씀해주세요.

2. 그리고 crawl_all 은 처음 뉴아라 생겼을 때만 돌렸었던 스크립트라, 수정하지 않으셔도 됩니다.

2021-08-07 10:33 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +
(위 전체 코멘트와는 별개로 이 형태를 그대로 가져간다면)

유저의 경우는 중복을 확인할 때 어쩔 수 없이 UserProfile 전체를 필터링해야하지만, article_exist를 확인하기 위해 모든 article에 대해 title, content_text 필터링을 하는 것은 매우 비효율적으로 보입니다. 애초에 글 필터링은 char 하나하나 직접 대조라, 모든 게시물 내용까지보기에는 시간도 매우 오래걸리고요.

공지글에서 겹치는 글은 보통 직전글(사실 시간도 정확히 겹침)인 경우가 많으므로 가져오는 글의 created_at 을 기준으로 가져와서 직전에 같은 글이 있으면 exist 처리하면 좋겠습니다. created_at 은 index도 걸려있기 때문에 성능도 나쁘지 않을 것 같구요.

2021-08-09 11:23 UTC, xhaktm3 commented on apps/core/management/scripts/portal_crawler.py
> +                print(f'crawled id: {a.id} - {a.title}')
article_exist는 기존에 같은 게시글이 있는지 확인하는 변수라 의미적으로는 밑에 들어가는게 맞는데, 어떤게 궁금하신건가요?

2021-08-09 11:25 UTC, jungnoh commented on apps/core/management/scripts/portal_crawler.py
> +                print(f'crawled id: {a.id} - {a.title}')
indent만 바뀌었길래 실수하신건가 해서요, 의도하신 거라면 상관없습니다 👍

2021-08-09 13:04 UTC, xhaktm3 commented on apps/core/management/scripts/portal_crawler.py
> +
>포탈 공지글들을 살펴보시면 같은 제목/내용의 글들은 같은 시간으로 올라오게 됩니다.

<img width="1157" alt="스크린샷 2021-08-08 오후 5 44 40" src="https://user-images.githubusercontent.com/66476231/128701738-64d824fc-7e82-4388-90c7-179afef634f4.png">

우선 같은 내용의 게시글들이 꼭 같은 시간에 올라오는 것은 아니었습니다. 같은 글들이 여러개 올라오는 이유는 게시자가 포탈의 여러 게시판에 올리기 때문인데, 그사이의 간격이 13분가량 되는게 있었고, 위 사진처럼 같은 게시글 사이에 다른 게시글이 올라오는 경우도 있어 created_at 기준으로 연속적이지 않을 수 있습니다.

따라서 가장 최근 크롤링된 포탈 게시글의 created_at 을 기준으로 크롤링 시작점을 잡아, 오늘 크롤링한 포탈글들 중에 같은 내용의 글들이 있는지 판단하여 bulk_crate하겠습니다. 제가 잘 이해하지못한 부분이 있으면 말씀해주세요.

2021-08-09 13:10 UTC, jessyoon14 commented
> * 그렇게 크롤러가 시작지점을 판단하게 되면, 지금처럼 get_or_create 하기보다는 한번에 Article object 들 만들어두고 bulk_create 하면 좋지 않을까 싶네요!
bulk_create를 알아봤는데, 제가 이해한 바로는 이 경우 AutoField인 article.id가 세팅되지 않아 사용할 수 없을 것 같습니다. 
기본 흐름은 말씀해주신대로 구현하되, bulk_create대신 일반 create를 여러번 사용해서 구현하겠습니다.

https://docs.djangoproject.com/en/3.2/ref/models/querysets/
> If the model’s primary key is an AutoField, the primary key attribute can only be retrieved on certain databases (currently PostgreSQL and MariaDB 10.5+). On other databases, it will not be set.

2021-08-10 00:35 UTC, victory-jooyon commented
> bulk_create를 알아봤는데, 제가 이해한 바로는 이 경우 AutoField인 article.id가 세팅되지 않아 사용할 수 없을 것 같습니다.

article을 생성하자마자 id 를 사용하는 곳이 있나요? 그게 아니라면 bulk create 을 이용하는게 성능면에서 훨씬 우수합니다. id가 영원히 생성이 안되는게 아니라, 시간이 아주 조금 지나서 id가 생성됩니다. (코드상으로 바로 사용하는게 아니면, 사용자는 느끼지 못할정도)

2021-08-10 00:48 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +
좋습니다! 감사합니다 :)

2021-08-10 00:50 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +
created_at 을 기준으로 간다면, 위와 같은 경우 (공지a와 공지c 내용이 같을 때)
공지a가 생성된 후, created_at 만 공지c의 created_at으로 덮어씌워진다고 생각하면 될까요?

2021-08-19 15:34 UTC, xhaktm3 commented on apps/core/management/scripts/portal_crawler.py
> +
연구실 인턴 마무리날이 다가와, 정신이 없었네요 ㅠㅠ... 늦게 답변드려 죄송합니다 :( 

앞서 말씀해주신 부분에서
> 하나의 article의 url 필드에 그중 가장 최신 공지글의 링크를 넣고, 그러면 링크를 활용해서 다음크롤러가 어디서부터 긁으면 되는지 판단할때 지금과 차이가 없게 될 것 같습니다.

article의 url 필드를 '변경' 또는 덮어씌워서 크롤러가 시작 지점을 판단하기보다, 매번 크롤링할때, 크롤링하여 db에 넣길 대기중인 article중에서, created_at이 db에 이미 들어간 보다 article의 created_at 최댓값보다 큰 게시글들 기준을 시작점으로 잡아, 중복확인의 시작점으로 잡았습니다.

말로 이해하기 어려운부분이 있어, 직접 코드를 보시면 이해가 빠를듯 합니다. 지수님께서 개별연구 마무리 후 바로 올려주실 것 같습니다.

2021-08-28 12:15 UTC, jessyoon14 commented on apps/core/management/scripts/portal_crawler.py
> +        a.save()
bulk_create()를 사용하려했으나, 이 경우 id가 늦게 부여되어 'created_at'을 바로 변경할 수가 없어 우선 created_by()만 사용하였습니다.

아래는 bulk_create()를 사용했던 코드입니다:
```
# 시도 1
articles = Article.objects.bulk_create(article_objects)
for i in range(len(articles)):
    articles[i].created_at = new_articles[i]['created_at']
Article.objects.bulk_update(articles, ['created_at'])

# 시도 2
articles = Article.objects.bulk_create(article_objects)
for i in range(len(articles)):
    articles[i].created_at = new_articles[i]['created_at']
    articles[i].save()
```
case1의 경우, `ValueError: All bulk_update() objects must have a primary key set.`가 일어나며, 공식 docs를 참고해보았을떄, bulk_update() 후 바로 id를 가져올 수 있는 기능이 아직 MySQL에 지원되지 않기때문인 것 같습니다. (https://docs.djangoproject.com/en/3.2/ref/models/querysets/)

case2의 경우, 에러는 없으나 DB의 필드가 업데이트 되지 않으며, 비슷하게 bulk_create의 id 문제가 아닐까 생각됩니다.

2021-08-28 12:21 UTC, jungnoh commented on apps/core/management/scripts/portal_crawler.py
> +        a.save()
`article_objects`가 뭔지 모르겠는데 일단 [8780fc2](https://github.com/sparcs-kaist/new-ara-api/blob/8780f2cf6a3b7e5b3f3c5d535b2a53042826ed55/apps/core/management/scripts/portal_crawler.py) 기준 `new_articles`이랑 똑같다고 생각하면,
```py
for i in range(len(articles)):
    article_objects[i]['created_at'] = new_articles[i]['created_at']
Article.objects.bulk_create(article_objects)
```
이렇게 바꾼다음에 저장하면 안될까요?

2021-08-28 12:26 UTC, jungnoh commented on apps/core/management/scripts/portal_crawler.py
> +        a.save()
결국 MetadataModel에 있는 `auto_now_add` 때문에 항상 `created_at`이 바뀌는 것이 문제 같은데, 이걸 대신 `default=timezone.now` 로 바꾸면 우리가 원하는 값으로 넣을 수 있을것 같거든요 ([reference](https://stackoverflow.com/questions/42219821/auto-now-add-fields-override-my-input))
이렇게 MetadataModel을 바꾸면 어떨까요? @victory-jooyon

2021-08-29 15:54 UTC, victory-jooyon requested changes

2021-08-29 15:54 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +                                            created_at__day = day.day)
이거 지금 day는 서울시기준인데, Article로 해서 가져오면 created_at 은 utc 예요. 그래서 서울시=utc 로 비교하는거라 로직상 문제가 있습니다.
그리고 year, month, day 다 하나씩 비교하는게 코드상 문제는 없긴한데, 이러면 where문 뒤에 조건이 더 붙는 형태라서 이것보다는 date의 00시 이상으로 필터링하는게 낫습니다.

2021-08-29 15:54 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +        a.save()
좋습니다.

2021-08-29 15:54 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +                                            created_at__day = day.day)
그리고 = 앞뒤로 스페이스가ㅠㅠ 꼼꼼히 살펴주세요.
그리고 따옴표 ' 대신 " 로 변경되어도 괜찮으니까 pre-commit 달아둔거 꼭 돌려주세요.

2021-08-29 15:54 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +        date_of_most_recent_portal_article_in_db = most_recent_portal_article_in_db.created_at
변수명이 길고 위에 변수랑 헷갈리는면이 있어서, 한줄로 하는게 더 뭘하고싶은지 알기 좋을 것 같아요.
`date_of_most_recent_portal_article_in_db = most_recent_portal_article_in_db.created_at if most_recent_portal_article_in_db else timezone.datetime.min.replace(tzinfo=timezone.utc)`

2021-08-29 15:54 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +                                                         content_text=info['content_text'])
이거 같은 제목+내용의 게시물이 연속적이지 않을때도 있나요? 연속적이라면 today_articles.last() 와만 title이랑 content_text 비교하면 될 것 같은데

2021-08-29 15:54 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +
그대로 둬도 괜찮은데, true/false 반환하는 함수인거면 predicate 이니까 `is_duplicate` 이나 `is_contained_in_list` 처럼 함수명이 `is` 같은걸로 시작하면 좋아요. 나중을 위해 참고!

2021-08-29 15:54 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +        a.save()
정훈님 말대로 수정후 migration 파일 같이 올려주시면 좋을것 같아요.

2021-08-29 15:54 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +        a.save()
좋습니다. 정훈님 말대로 수정후 migration 파일 같이 올려주시면 좋을것 같아요.

2021-08-29 16:00 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +                                                         content_text=info['content_text'])
이게 위에 water님이 올려주신 다른 댓글과 내용이 이어지는것 같은데,
> 우선 같은 내용의 게시글들이 꼭 같은 시간에 올라오는 것은 아니었습니다. 같은 글들이 여러개 올라오는 이유는 게시자가 포탈의 여러 게시판에 올리기 때문인데, 그사이의 간격이 13분가량 되는게 있었고, 위 사진처럼 같은 게시글 사이에 다른 게시글이 올라오는 경우도 있어 created_at 기준으로 연속적이지 않을 수 있습니다.

라고 하셨는데, 이 issue가 시작된게, created_at이 정확히 같은 게시물이 여러개 올라올때 side_articles 를 제대로 못찾는 경우였잖아요? 그러니까 게시물이 서로 떨어져있고, created_at이 다르다면, 어차피 issue를 일으키지 않으므로,
우리 입장에서는 연산을 최소화하기 위해서 today_articles 전체의 content를 비교하는 비싼연산을 하기보다는 today_articles의 마지막과만 비교해도 되지 않을까 생각합니다!

2021-09-02 11:33 UTC, jessyoon14 commented on apps/core/management/scripts/portal_crawler.py
> +        a.save()
@jungnoh @victory-jooyon 
jungnoh님 말씀대로 수정하려고 살펴봤는데, `models.py` line 14을 보니, bulk_create 함수는 이미 timezone.now를 사용합니다.:

```
# models.py

class MetaDataQuerySet(models.QuerySet):
    def delete(self):
        return super().update(**{
            'deleted_at': timezone.now(),
        })

    def hard_delete(self):
        return super().delete()

    def bulk_create(self, objs, batch_size=None, ignore_conflicts=False):
        for obj in objs:
            if not hasattr(obj, 'created_at'):
                obj.created_at = timezone.now()

        return super().bulk_create(objs, batch_size)
```

> 결국 MetadataModel.created_at에 있는 auto_now_add 때문에 항상 created_at이 바뀌는 것이 문제 같은데, 이걸 대신 default=timezone.now 로 바꾸면 우리가 원하는 값으로 넣을 수 있을것 같거든요 (reference)

이게 지금 bulk_create에서 되어있는거 아닌가요?

2021-09-02 13:02 UTC, jungnoh-maasasia commented on apps/core/management/scripts/portal_crawler.py
> +        a.save()
저거 하고 마이그레이션 잊지 말고 만들어주세요~!

2021-09-02 17:04 UTC, jessyoon14 commented on apps/core/management/scripts/portal_crawler.py
> +                                                         content_text=info['content_text'])
이 issue가 시작된 것은 created_at이 정확히 같은 게시물이 여러개 올라올때 side_articles 를 제대로 못찾아서였지만, 윤수님과 작업하는 과정에서 텍스트가 중복되는 포탈글들이 너무 많이 올라오는게 게시판을 보기 안좋게 만든다고 판단하여 중복텍스트의 글을 없애자는 목표를 추가하였습니다. 그래서 텍스트가 서로 떨어져있고 created_at이 다르더라도 중복글을 방지하려고 합니다. 하루에 올라오는 포탈 글의 수가 30개 이하임을 고려했을때, 이 정도 연산까지는 고려할 수 있다고 생각합니다. 

혹시 이에 대해 반대하시면 윤수님과 다시 상의해보겠습니다.

2021-09-03 02:13 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +                                                         content_text=info['content_text'])
연속해서 올리지 않고, 시간이 지난 후에 다시 올린다면 다시 올리는 이유가 있지 않을까요? (끌올 같은 개념이라던가, 마감시간 직전에 다시 올린다던가) 평균적으로 포탈 개수가 30개 이하이지만, 글 하나가 미친듯이 길거나 어느날 포탈 글 개수가 많이 올라오면 충분히 비싼연산이라고 생각하기 때문에 일단 연속한 중복글만 없애도 지금보다는 충분히 쾌적할거라고 생각합니다.

2021-09-03 02:16 UTC, victory-jooyon requested changes

2021-09-03 02:16 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +
@jessyoon14 이거 제가 설명을 제대로 못한 것 같아요. is_ 로 시작하면 좋을 것 같다는건 "list_contains_article" 같은 predicate 함수이고, 지금 "is_contained_in_db"처럼 수정하신건 이전 명명처럼 가는게 맞습니다. predicate이 아닌 article 집합이니까요.

2021-09-03 16:51 UTC, jessyoon14 commented on apps/core/management/scripts/portal_crawler.py
> +
앗 이건 제가 더 꼼꼼히 살펴봤어야됬는데 기계적으로 수정했네요ㅜㅜ

2021-09-06 07:09 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +                                                         content_text=info['content_text'])
@victory-jooyon 이부분 확인하시면 다시 리뷰할게요.

2021-09-06 07:09 UTC, victory-jooyon commented on apps/core/management/scripts/portal_crawler.py
> +                                                         content_text=info['content_text'])
@jessyoon14  이부분 확인하시면 다시 리뷰할게요.

2021-09-06 12:51 UTC, jessyoon14 commented on apps/core/management/scripts/portal_crawler.py
> +                                                         content_text=info['content_text'])
피드백 감사합니다. water님과 얘기한 결과, 연속된것만 처리하기로 결정했어요. 지금 수정해서 다시 올릴게요

2021-09-06 15:04 UTC, jessyoon14 commented
@victory-jooyon @xhaktm3 

서로 같은 제목을 가진 포탈글 중 연속되는 중복만 삭제하도록 수정했습니다.
연속되는 중복의 경우, 제일 최근 글만 DB에 들어갑니다.
두 크롤링 시점의 경계선에 걸친 연속된 중복글도 확인하고, 최근 글로 업데이트합니다.
긴 PR인데 지금까지 꼼꼼하게 리뷰해주셔서 감사합니다. 한번만 더 리뷰 부탁드립니다!

2021-09-09 10:58 UTC, jungnoh approved these changes
수정하신 케이스 전부 잘 작동되는 것 확인했습니다.
테스트를 붙이면 좋겠는데, 특성상 머지 되고 다른 브랜치에서 리팩토링 하고 나서 짜면 좋을 것 같아요~

2021-09-13 07:15 UTC, merged