scrap의 side_articles 문제 해결
sparcs-kaist/new-ara-api pull request #231
Opened 2021-08-07 07:18 UTC by xhaktm3

issue #228
fromview=scrap 에서 보이는 side_article의 after,before를 결정짓는 순서가 article table의 created_at으로 되어있던 것을 scrap table의 created_at을 참조하도록 변경하였습니다.

테스트코드 작성하였습니다.

2021-08-07 09:14 UTC, jungnoh requested changes

2021-08-07 09:14 UTC, jungnoh commented on apps/core/serializers/article.py
> +                before = articles.filter(scrap_set__created_at__lte=obj.scrap_set.get().created_at).first()
`obj.scrap_set.get()` 두번쓰면 쿼리가 두번 나갈거에요
244라인 전에 `obj.scrap_set.get().created_at`를 변수에 저장하고 변수값을 이용하는 것이 좋아보입니다

2021-08-07 10:03 UTC, victory-jooyon commented
정훈님이 리뷰 잘 주셨네요. 리뷰 수정 하시면 확인 후 approve 하겠습니다.

2021-08-09 11:05 UTC, xhaktm3 commented on apps/core/serializers/article.py
> +                articles = articles.exclude(id=obj.id)
수정했습니다.

2021-08-09 11:16 UTC, xhaktm3 commented on apps/core/serializers/article.py
> +                before = articles.filter(scrap_set__created_at__lte=obj.scrap_set.get().created_at).first()
수정했습니다.

2021-08-09 11:26 UTC, jungnoh approved these changes

2021-08-18 02:47 UTC, victory-jooyon requested changes

2021-08-18 02:47 UTC, victory-jooyon commented on apps/core/serializers/article.py
> +                scrap_obj_created_at = obj.scrap_set.get().created_at
obj.scrap_set 이 여러개인경우, .get()을 하면 에러가 납니다.

2021-09-05 14:52 UTC, xhaktm3 commented on apps/core/serializers/article.py
> +                scrap_obj_created_at = obj.scrap_set.get().created_at
scrap_set을 사용하는 기존의 created_at 비교를 삭제하고, Scrap table에서 created_at을 비교하도록 수정하였습니다.
obj.scrap_set이 여러개일 경우는 여러명의 사용자가 스크랩할 경우이므로 관련 테스트 코드 작성하였습니다.
테스팅과정중에 call_back issue가 발생해 늦은 답변 죄송합니다..

2021-09-09 11:08 UTC, jungnoh approved these changes
짜주신 테스트 통과하면 문제 없을것 같아요. 수고하셨습니다~!

2021-09-15 13:13 UTC, merged