Preserve sub_comment when parent_comment deleted
sparcs-kaist/new-ara-api pull request #244
Opened 2021-09-14 12:16 UTC by xhaktm3

Handle #239 

Add new model class 'AllQueryMetaDataModel' for Comment table.

2021-09-14 18:52 UTC, xhaktm3 commented
현재 article model의 comment count에 삭제된 댓글은 포함하지않았습니다. 따라서 삭제된 댓글이 보이지만 개수는 보기와 달라집니다. 프론트단에서 코멘트 개수가 0인 게시글은 댓글이 안보이고 '댓글이 없습니다'라고 뜨는데, 댓글이 0개여도 삭제된 댓글이 있을 수 있으므로 프론트에서 댓글목록을 항상 가져오도록 해야합니다.

2021-09-16 13:42 UTC, jungnoh requested changes
우선 PR을 작성하실 때는 정확히 어떤 작업을 하셨는지 상세히 설명해 주셨으면 좋겠습니다. 회의에 참석하지 않으신 분들도 이해할 수 있도록 맥락을 주기 위함입니다.

설계에 대해 이야기해보면, 지금과 같은 상황에서는 `AllQueryMetaDataModel`가 기존의 `QueryMetaDataModel` 과 기능상의 차이가 전혀 없습니다. 삭제 처리를 하는데 있어 로직의 차이가 있는것도 아니고, 부모 클래스의 특성을 이용해서 어떤 작업을 하는것도 아닙니다. 제가 지난주 회의에서 별도의 base (abstract) model을 만드는 설계를 하면 좋겠다고 말씀드린 것은 그 abstract model에 이런 로직들의 차이를 담는 방식으로 설계하면 좋겠다는 의미였습니다. 그런데 지금 답글이 삭제되지 않도록 하는 부분은 signal에 모든 로직이 있기 때문에, `AllQueryMetadataModel`은 전혀 불필요한 클래스가 됩니다.

추가로 댓글이 삭제되었을 때 나오는 메세지에 대한 테스트 케이스도 필요해 보입니다.

2021-09-23 11:12 UTC, jessyoon14 commented
수고하셨습니다. 저도 jungnoh님 코멘트에 동의합니다. signal의 로직이 `AllQueryMetadataModel`안에 담기거나, 아예 새롭게 `AllQueryMetadataModel`을 없애는 방향으로 수정 완료되시면 리뷰 드릴게요!

2021-09-24 03:11 UTC, victory-jooyon commented
signal의 로직이 모델쪽으로 옮겨오는건 반대입니다. 일단 close하시고 나중에 필요할때 다시 작업하는건 어떨까요?
그리고 
![image](https://user-images.githubusercontent.com/33751269/134612391-1eaa4ed3-1c57-4daf-ad5b-1d2e80334e49.png)

이런경우 커밋을 하나로 squash 시키는 것이 좋습니다.

2021-09-26 15:22 UTC, xhaktm3 commented
설명이 부족했던 점 죄송합니다. 
회의에서 논의되었던 방향은 대댓글의 위치와 내용을 보존하기위해(대댓글의 위치를 보존하려면 참조중인 댓글이 삭제되더라도 참조가 가능해야함), comment 모델이 deleted_at이 min값이 아닌 인스턴스도 get() 할수 있는 custom model을 상속하도록 결정하였습니다. 

따라서 제가 구현한 AllQueryMetaDataModel의 기존 MetaDataModel의 차이점은 "Do not delete cascade sub comment"에 적용된 AllQueryMetaDataModel의 objects = MetaDataQuerySet.as_manager() 라인 밖에 없습니다. 기존 MetaDataModel은 custom queryset을 정의하고, get시 delete_at이 min이 아닌 인스턴스는 가져오지말자고 정의된 custom manager를 사용합니다. 따라서 저희목적에 맞게 custom manager을 쓰지않고 custom queryset만을 manager로 사용하자는 함수가 QuerySet.as_manager()함수입니다.

AllQueryMetaDataModel을 사용함으로써 대댓글의 위치가 보존됩니다. 이후 대댓글의 내용을 보존하기 위해서 기존 comment signal에서 post_save이후 해당 instance의 deleted_at이 min값이 아닐경우 대댓글을 삭제한다는 부분을 없애야했습니다.

@jungnoh 이러한 의미에서 AllQueryMetaDataModel과 기존 MetaDataModel이 로직상 의미는 다르다고 생각했습니다. 그리고 목적에 맞게 답글을 삭제하는 부분이 signal에 모든 로직이 있는 건 아닌것 같습니다. 제가 잘못이해한 부분이 있다면 말씀해주세요

2021-09-26 15:27 UTC, xhaktm3 commented
다음부터 PR열 때는 설명을 자세히 쓰도록하겠습니다  😔 😔

2021-09-26 15:42 UTC, jungnoh requested changes
- `AllQueryMetaDataModel`과 `QueryMetaDataModel`에 로직 차이가 전혀 없습니다. 그렇기 떄문에 클래스를 분리하는 것은 기능상 의미가 없어보입니다.
- 답글 삭제 안하도록 하는 것 = cascade를 안함 -> 이부분은 전부 signal에 있음 -> signal에 모든 로직이 있음
이라는 뜻입니다. 나머지 변경하신 부분은 결과에 따른 presentation쪽 부분이라 로직과는 거리가 먼 것으로 보입니다.

다시 설명을 드리면, 부모 클래스를 나눈다는 것은 **부모 클래스와 관련된 부분에서 달라지는 것이 있기 때문에 나누는 것입니다**. 부모 클래스에서 로직이 달라져서 빼는 것일수도 있고, 상속을 이용해서 다형성을 가지고 처리를 다르게 하는것일수도 있습니다. 그런데 이 경우에는 부모 클래스에서 달라지는 부분이 없고, 그렇기 때문에 클래스를 나누는 것은 불필요한 변경입니다.
또한 signal에 로직 변경이 **전부 있는것이 맞고**, 이게 나쁜 디자인도 아니라고 생각되기 때문에 `AllQueryMetaDataModel`이 있을 필요가 더더욱 없습니다.

2021-09-26 15:46 UTC, jungnoh commented
추가로 말씀드리면 매니저 부분은 AllQueryMetadataModel에 두지 말고 Comment에 둬도 충분할 것 같습니다.

2021-09-27 06:05 UTC, xhaktm3 commented
@jungnoh "로직 처리를 위임할 대상만 달라졌다고 보입니다" 라고 말씀해주신 정훈님 의견이 옳다고 생각합니다. 말씀해주신대로 AllQueryMetaDataModel을 삭제하고 기존 MetaDataModel을 참조하되 comment에서는 objects = MetadataQueryset.as_manager() 라인을 추가하겠습니다.

2021-09-27 06:40 UTC, victory-jooyon commented
이 브랜치를 계속 유지한 상태로 수정을 계획하신다면, 필요없는 커밋들 drop을 시켜도될것 같긴합니다. git rebase의 interactive 옵션을 활용해보지 않으셨다면 이 기회에 배워보는것도 좋을 것 같구요!

2021-09-27 06:58 UTC, xhaktm3 commented
@victory-jooyon 위에서 말씀해주신 Fix test flaw부분은 squash 했으나, 다른 커밋들은 삭제된 AllQueryMetaDataModel이외도 i18n이나 signal의 수정사항들이 필요해 하나라도 drop시키면 처음부터 순서대로 작성할 필요가 있어보여요. 그래도 drop이 필요해는 부분이 있다면 콕 찝어서 말씀해주시면 감사하겠습니다!

squash하면서 git rebase의 interactive 옵션에 대해서 알 수 있었습니다. 👍

2021-09-27 07:04 UTC, xhaktm3 commented
@jungnoh 삭제되었을 때 발생하는 메세지는 어떤 메세지를 말씀하시는 건가요? admin page에서 삭제시 발생하는 메시지인가요? 프론트나 백에서 유저가 메시지를 삭제했을때 따로 메세지가 뜨지는 않는것 같습니다.

2021-09-27 07:06 UTC, jungnoh commented on apps/core/serializers/comment.py
> +
그냥 요런것들이요

2021-09-27 07:52 UTC, xhaktm3 commented on apps/core/serializers/comment.py
> +
아하 알겠습니당

2021-09-27 12:43 UTC, jungnoh approved these changes

2021-09-27 12:43 UTC, jungnoh commented
수고하셨습니다~!

2021-09-27 12:46 UTC, merged