Prevent realname comment on anonymous article/comment
sparcs-kaist/new-ara-api pull request #289
Opened 2021-11-10 05:14 UTC by jessyoon14

백엔드에서 댓글의 익명 여부는 프론트에서 보내주는 is_anonymous 필드로 결정합니다.

지난 론칭때, 익명 게시판의 댓글이 실명으로 들어간 문제는 아마도 프론트에서 is_anonymous를 잘못 보내준 것이 아닐까 생각합니다.

여기서는 프론트에서 is_anonymous가 잘못 들어오더라도, 백에서 다시 확인해서 익명 글 / 익명 댓글에 대한 댓글은 is_anonymous 필드를 True로 바꿔줍니다.

2021-11-15 12:44 UTC, jessyoon14 commented on apps/core/views/viewsets/comment.py
> +            if (not parent_article_is_anonymous) and (not parent_comment_is_anonymous):
@jungnoh 반영했습니다. 전반적인 방향성 (프론트가 주는 `is_anonymous` parameter를 무시하는 것)에 대해서는 어떻게 생각하시나요?

2021-11-15 15:23 UTC, jungnoh commented on apps/core/views/viewsets/comment.py
> +            if (not parent_article_is_anonymous) and (not parent_comment_is_anonymous):
무시할거면 그냥 파라미터 없애도 되지 않나요? 무시하는 값 그냥 놔두면 레거시인데

2021-11-15 15:24 UTC, jungnoh requested changes
항상 무시할거면 그냥 파라미터 없애도 되지 않나요? 무시하는 값 그냥 놔두면 레거시에요

2021-11-22 15:04 UTC, jessyoon14 commented
@jungnoh 코멘트에 대해서 프론트에서 `is_anonymous`를 받지 않도록 수정했습니다.
게시글에 대해서 프론트에서 `is_anonymous`를 받지 않도록 수정하는 것은 PR #290 에 남겨주신 코멘트 대로, board table에 익명 column 추가하는 수정까지 합해서 @iv-y 님께서 작업하기로 했습니다.  

프론트에서 `is_anonymous`를 주지 않는 것은 티켓으로 남겨놓았습니다.

2021-11-25 01:15 UTC, jungnoh approved these changes

2021-11-29 10:48 UTC, merged