Feature/permission NEW permission system
sparcs-kaist/new-ara-api pull request #440
Opened 2024-01-09 14:55 UTC by DoyunShin

2024-01-16 13:28 UTC, ddungiii reviewed
와우... 정말 큰 작업을 했네
많아서 user만 먼저 리뷰했습니다

2024-01-16 13:28 UTC, ddungiii commented on apps/user/models/usergroup.py
> +
Django 문법은 정확히는 잘 모르긴 하는데, 찾아보니까 join 해서 가져오는거
`Group.objects.filter(usergroup__user_id=self.user.id)`
처럼 사용할 수 있는 것 같은데, 확인 부탁드려용 (바꿔서 make test 했을 땐 잘 돌아감)

2024-01-16 13:28 UTC, ddungiii commented on apps/user/models/usergroup.py
> +        return users
얘두

2024-01-16 13:28 UTC, ddungiii commented on apps/user/models/user_profile.py
> +        return UserGroup.search_by_user(self.user)
이건 cached_property 써도 좋지 않을까요?

2024-01-16 13:28 UTC, ddungiii commented on apps/user/models/user_profile.py
> +    def has_group_by_name(self, name: str) -> bool:
```suggestion
    def has_group_by_name(self, group_name: str) -> bool:
```
group_name 이면 좀 더 직관적일 것 같아요

2024-01-16 13:28 UTC, ddungiii commented on apps/user/models/user_profile.py
> +        self.add_group(group)
```suggestion
    def add_group_by_name(self, group_name: str) -> None:
        group = Group.search_by_name(name)
        self.add_group(group)
```
얘도?

2024-01-16 13:28 UTC, ddungiii commented on apps/user/models/user_profile.py
> +        self.remove_group(group)
얘도?

2024-01-16 13:28 UTC, ddungiii commented on apps/user/models/user_profile.py
> +        return False
```suggestion
        return any(group.is_official for group in self.groups())
```

2024-01-16 13:28 UTC, ddungiii commented on apps/user/models/user_profile.py
> +        return any([group.name == name for group in self.groups()])
```suggestion
        return any(group.name == name for group in self.groups())
```
memory에 list 안띄우고 바로 쓸 수 있는 것 같은데 어떤가요?

2024-01-16 13:28 UTC, ddungiii commented on apps/user/models/user_profile.py
> +        return any([group.group_id == group_id for group in self.groups()])
얘도?

2024-01-16 13:28 UTC, ddungiii commented on apps/user/models/user/manual.py
> +        blank=True,
얜 왜 null인가요? null이랑 1 (unauth)랑 다른게 있을까요?

2024-01-16 13:28 UTC, ddungiii commented on apps/user/migrations/0022_group_remove_userprofile_group_and_more.py
> +    }
https://github.com/sparcs-kaist/new-ara-api/blob/06fc5875a581656a3370db25bb7d514fe6e5b99a/apps/user/models/user_profile.py#L42

`is_official` 2, 4가 되어야하지 않을까요? 뭔가 정책이 바꼈나요

2024-01-16 13:28 UTC, ddungiii commented on apps/user/migrations/0022_group_remove_userprofile_group_and_more.py
> +
그리고 row로 관리하는 건 좋은데, group constant를 어디 만들어두고 관리하면 좋지 않을까요? magic number를 쓰는 곳이 많이 보여서, 나중에 관리가 어렵지 않을까 싶습니다

2024-01-16 13:28 UTC, ddungiii commented on apps/user/migrations/0022_group_remove_userprofile_group_and_more.py
> +        WHERE (a.group+1) = b.group_id;
raw query 쓸 때 alias로 `a`, `b` 보다는 의미있게 쓰면 조금 더 좋지 않을까요
뭐 짧아서 상관없긴 한데..

2024-01-16 13:28 UTC, ddungiii commented on apps/user/migrations/0022_group_remove_userprofile_group_and_more.py
> +    # schema_editor.connection.commit()
필요한 주석일까요?

2024-01-16 13:38 UTC, DoyunShin commented on apps/user/migrations/0022_group_remove_userprofile_group_and_more.py
> +
원래 이게 기존 방식입니다.
```python
    class UserGroup(models.IntegerChoices):
        # 뉴아라 계정을 만들지 않은 사람들
        UNAUTHORIZED = 0, gettext_lazy("Unauthorized user")
        # 카이스트 메일을 가진 사람 (학생, 교직원)
        KAIST_MEMBER = 1, gettext_lazy("KAIST member")
        # 교내 입주 업체 직원
        STORE_EMPLOYEE = 2, gettext_lazy("Store employee")
        # 카이스트 메일이 없는 개인 (특수한 관련자 등)
        OTHER_MEMBER = 3, gettext_lazy("Other member")
        # 교내 학생 단체들
        KAIST_ORG = 4, gettext_lazy("KAIST organization")
        # 외부인 (홍보 계정 등)
        EXTERNAL_ORG = 5, gettext_lazy("External organization")
        # 소통게시판 관리인
        COMMUNICATION_BOARD_ADMIN = 6, gettext_lazy("Communication board admin")
        # 뉴스게시판 관리인
        NEWS_BOARD_ADMIN = 7, gettext_lazy("News board admin")
``` 

하지만 이 방식으로 할 경우 그룹 추가될 경우에는 저것들에도 다 반영을 해줘야 됩니다.
이번에 그룹 작업한 이유가 요거 제거하고 board permission에서 사용하던 bitmask 제거하고 db상에서 바로 퍼미션 확인할 수 있도록, 그리고 그룹 추가해도 다른 시스템에 문제가 없도록 하기 위해서입니다.
이거는 다른분들 의견 한번 들어봐도 될 듯 하네요

2024-01-16 13:40 UTC, DoyunShin commented on apps/user/models/group.py
> +        return Group.objects.filter(name=name)
코드 상에 group name을 사용해서 구분하는 경우가 없을것 같아서 unique를 빼뒀습니다.
만약 group name으로도 검색할 수 있도록 할거라면 unique넣고 migration파일에 name들을 대문자들로 수정하면 될 듯 합니다.

2024-01-16 13:40 UTC, DoyunShin commented on apps/user/models/usergroup.py
> +
확인해보겠습니다.

2024-01-16 13:40 UTC, DoyunShin commented on apps/user/models/usergroup.py
> +        return users
확인해보겠습니다.

2024-01-16 13:40 UTC, DoyunShin commented on apps/user/models/user_profile.py
> +        return UserGroup.search_by_user(self.user)
넵

2024-01-16 13:42 UTC, DoyunShin commented on apps/user/models/user_profile.py
> +        return False
수정하겠습니다.

2024-01-16 13:43 UTC, DoyunShin commented on apps/user/models/user_profile.py
> +    def has_group_by_name(self, name: str) -> bool:
수정하겠습니다.

2024-01-16 13:44 UTC, DoyunShin commented on apps/user/models/user_profile.py
> +        return any([group.name == name for group in self.groups()])
수정하겠습니다.

2024-01-16 13:53 UTC, DoyunShin commented on apps/user/models/usergroup.py
> +
Group하고 UserProfile을 import하면 partially initialized module 문제가 발생할 수 있어서 웬만하면 권장되진 않는데, 일단 가능은 합니다.
```python
Group.objects.filter(usergroup__user=user).all()
```

바꿀까요?

2024-01-16 13:54 UTC, DoyunShin commented on apps/user/models/user_profile.py
> +        self.add_group(group)
수정하겠습니다.

2024-01-16 13:54 UTC, DoyunShin commented on apps/user/models/user_profile.py
> +        return any([group.group_id == group_id for group in self.groups()])
수정하겠습니다.

2024-01-16 13:57 UTC, DoyunShin commented on apps/user/models/user/manual.py
> +        blank=True,
잘못 추가하였네요.. 삭제하겠습니다.

2024-01-16 14:04 UTC, DoyunShin commented on apps/user/models/user_profile.py
> +        self.remove_group(group)
수정하겠습니다.

2024-01-16 14:07 UTC, ddungiii commented on apps/user/models/group.py
> +        return Group.objects.filter(name=name)
아 저도 unique가 필요해보이진 않는데, list로 반환하길래 물어봤어요

name이 같은 group이 없는게 보장되면 `search_by_name`도 Group 만 반환하는건 어떨까요?
사용하는 곳에서도 group으로 사용하는데 list["group"]을 반환하고 있었네요. 이건 문제 없나요?

2024-01-16 14:08 UTC, DoyunShin commented on apps/user/models/group.py
> +        return Group.objects.filter(name=name)
(디스코드 Group기능을 참고하여 생각했음)

2024-01-16 14:09 UTC, ddungiii commented on apps/user/migrations/0022_group_remove_userprofile_group_and_more.py
> +    }
아 2,4 가 아니라 여기선 3,5네
위처럼 기존코드에서 `OFFICIAL_GROUPS = [UserGroup.STORE_EMPLOYEE, UserGroup.KAIST_ORG]` 인데,
KAIST organization (4), External organization(5)가 True여서요
Store employee (3), KAIST organization (4) 가 True이어야 하지 않을까요?

2024-01-16 14:10 UTC, ddungiii commented on apps/user/migrations/0022_group_remove_userprofile_group_and_more.py
> +
요건 얘기 해보시죵
DB에서 확인하는건 좋은데, 그러면 코드에서 Group을 특정해서 사용해야할 때는 1,2,3 계속 integer로 사용해야하다보니 실수가 생길 수 있을 것 같아서요

2024-01-16 14:14 UTC, DoyunShin commented on apps/user/migrations/0022_group_remove_userprofile_group_and_more.py
> +        WHERE (a.group+1) = b.group_id;
짧아서 괜찮을 듯 합니다

2024-01-16 14:15 UTC, DoyunShin commented on apps/user/migrations/0022_group_remove_userprofile_group_and_more.py
> +    }
앗 수정하겠습니다.

2024-01-16 14:31 UTC, DoyunShin commented on apps/user/models/usergroup.py
> +
수정하겠습니다.

2024-01-16 14:31 UTC, DoyunShin commented on apps/user/models/usergroup.py
> +        return users
수정하겠습니다.

2024-01-23 14:14 UTC, injoonH commented on apps/user/models/group.py
> +        return Group.objects.filter(name=name)
현재 코드에서는 `Group.search_by_name()`이 사용되는 곳이 없군요.

2024-01-27 06:25 UTC, DoyunShin commented on apps/user/migrations/0022_group_remove_userprofile_group_and_more.py
> +
최대한 코드상에서 id를 사용한 처리를 안하기로 하였습니다.
나중에 TF로 로그인 시 이메일에 따라서 어떤 역할(그룹)을 줘야되는지 처리되도록 만들어두겠습니다.
또한 현재 ID 7번인 "소통게시판 관리인(카이스트 직원)"에 관련된 보드같은 경우에는 최대한 userprofile로 is_school_admin을 빼뒀지만, 거기는 **특수 게시판** 이므로 어쩔 수 없이 사용되어야만 합니다.

2024-01-27 06:25 UTC, DoyunShin commented on apps/user/migrations/0022_group_remove_userprofile_group_and_more.py
> +
또한 현재 ID 7번인 "소통게시판 관리인(카이스트 직원)"에 관련된 보드같은 경우에는 최대한 userprofile로 is_school_admin을 빼뒀지만, 거기는 **특수 게시판** 이므로 어쩔 수 없이 사용되어야만 합니다.

2024-04-28 06:25 UTC, injoonH requested changes

2024-04-28 06:25 UTC, injoonH commented on apps/core/migrations/0058_remove_board_comment_access_mask_and_more.py
> +# Generated by Django 4.2.3 on 2024-01-10 17:16
❗ 파일명 `0059_remove_board_comment_access_mask_and_more.py`로 수정해야 합니다.

2025-06-02 20:00 UTC, sjsh16kw commented on apps/user/views/viewsets/user.py
>              # 2. 아직 승인 이전, 회원가입을 시도했던 공용 계정 회원
로그인 부분 (line 214 ~ line 228)에서 model에 group filed를 삭제하게 된다면, 이미 가입이 되어있는 user_profile의 경우 (is_activate가 True로 설정된 user_profile에 대해서...) permission이 업데이트 되지 않아 문제가 생길 것 같습니다. 이 부분에서 새로 바뀐 policy에 따라 null 여부를 체크하고 permission을 부여하는 예외 처리가 필요할 것 같습니다.

2025-06-02 20:01 UTC, sjsh16kw commented on apps/user/views/viewsets/user.py
>                  user_profile.save()
remove_group_by_id 이 부분하고 soft delete 정책 관련 Conflict 다시 한 번 확인 부탁드리고, 또 is_maual, is_kaist 조건에 걸리지 않았을 경우 permission이 누락될 수도 있을 것 같아, 예외 처리가 필요할 것 같습니다.

2025-06-02 20:04 UTC, sjsh16kw commented on apps/user/admin.py
> +class UserGroupAdmin(admin.ModelAdmin):
이 부분도 base repository를 사용할 수 있을까요?

2025-06-02 20:06 UTC, sjsh16kw commented on apps/user/admin.py
> +class GroupAdmin(admin.ModelAdmin):
이 부분도 다시 Base Model 사용 가능할까요?

2025-06-02 20:12 UTC, sjsh16kw commented on apps/user/models/user_profile.py
> +    def groups(self) -> list[Group]:
제 기억상 method의 naming comvention이 동사로 시작이였던 것 같은데, email이랑 groups는 앞에 get_ 붙여도 좋을 것 같습니다! (필수 사항은 아니에요.)

2025-07-13 09:44 UTC, closed without merging