feat: Create notification FastAPI
sparcs-kaist/new-ara-api pull request #468
Opened 2024-04-28 14:30 UTC by Qndndn

Create notification FastAPI.v2

2024-04-29 00:08 UTC, hyukychang reviewed
일단 코드가 돌아가는지 확인해 주세요

2024-04-29 00:08 UTC, hyukychang commented on ara/infra/notification/notification_infra.py
> +    )
is_read 값은 왜 항상 false 인가요?

2024-04-29 00:08 UTC, hyukychang commented on ara/infra/notification/notification_infra.py
> +            ).select_related(
`self`에는 유저가 없어 보여요 ㅠㅠ

2024-04-29 00:08 UTC, hyukychang commented on ara/infra/notification/notification_infra.py
> +
notification과 notificationReadLog랑은 무슨 차이가 있나요??

2024-05-17 02:42 UTC, hyukychang requested changes

2024-05-17 02:42 UTC, hyukychang commented on ara/infra/notification/notification_infra.py
> +        ]
요거 N+1 쿼리일 가능성이 높아 보이는데 시간 나면 리팩토링 하거나 TODO 체크해주세요 👍

2024-05-17 02:42 UTC, hyukychang commented on ara/infra/notification/notification_infra.py
> +            return "익명"
"실명", "nickname", "익명" 전부다 constant로 지정해서 사용해주세요!!!!

2024-05-17 02:42 UTC, hyukychang commented on ara/infra/notification/notification_infra.py
> +        def notify_article_commented(_parent_article: Article, _comment: Comment):
변수에 왜 _가 들어있나요?

2024-05-17 02:42 UTC, hyukychang commented on ara/infra/notification/notification_infra.py
> +    def get_display_name(self, article: Article, profile: int):
이거는 외부로 노출(domain 이나 다른 infra layer에서 사용할거 같아 보이는게 아닌)되지 않으면 함수명에 _ 붙여 주세요

2024-05-17 02:42 UTC, hyukychang commented on ara/infra/notification/notification_infra.py
> +    def create_notification(self, comment: Comment) -> None:
이거 transaction이 붙어야 할거 같아요 음... 근데 이거는 어려울 수도 있으니까 같이 한번 봐요

2024-05-20 03:55 UTC, Qndndn commented on ara/infra/notification/notification_infra.py
> +    def create_notification(self, comment: Comment) -> None:
넵~!

2025-06-02 23:00 UTC, sjsh16kw commented
django ninja로의 migration이 잠정 중단됨에 따라 PR을 임시로 Close 합니다.

2025-06-02 23:00 UTC, sjsh16kw commented
django ninja로의 migration이 잠정 중단됨에 따라 PR을 임시로 Close 합니다.

2025-06-02 23:00 UTC, sjsh16kw commented
django ninja로의 migration이 잠정 중단됨에 따라 PR을 임시로 Close 합니다.

2025-06-02 23:00 UTC, closed without merging